routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/home', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@login_user')->name('login');
Route::get('/loginUser', 'Auth\LoginController@loginUser')->name('loginUser');
Route::get('/registerUser', 'Auth\LoginController@registerUser')->name('registerUser');
Route::get('/logout', 'Auth\LoginController@logout')->name('user.logout');

Route::group(['middleware' => ['check-permission']], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/role/delete/{id}', 'RoleController@delete')->name('role.delete');
    Route::resource('/role', 'RoleController');
    Route::resource('/user', 'UserController');
    Route::get('/server/delete/{id}', 'ServerController@delete')->name('server.delete');
    Route::resource('/server', 'ServerController');

});

Route::get('/generate_password', 'GeneratePasswordController@generate_password')->name('generate.password');
Route::get('/check_server_creds/{email}/{ip_addr}', 'GeneratePasswordController@check_server_creds')->name('check.server_creds');
Route::get('/check_otp/{otp}/{id}', 'GeneratePasswordController@check_otp')->name('check.otp');

app/Roles.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Roles extends Model
{
    use SoftDeletes;
    protected $table = 'roles';
    protected $primaryKey = 'id';

    protected $dates = ['deleted_at'];

    public function permission()
    {
        return $this->belongsToMany('App\Permissions', 'role_permissions', 'role_id', 'permission_id');
    }

//    public function permissions()
//    {
//        return $this->belongsTo('App\RolePermission', 'id', 'role_id');
//    }

    public function role_permissions()
    {
        return $this->hasMany('App\RolePermission', 'role_id', 'id');
    }

    public function parent()
    {
        return $this->belongsTo('App\Role', 'parent_id', 'id');
    }

    public function child()
    {
        return $this->belongsTo('App\Role', 'id', 'parent_id');
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Permissions;
use App\RolePermission;
use Illuminate\Http\Request;
use App\Roles;
use Config;
use Route;
use Yajra\DataTables\DataTables;
use App\Services\CustomRouteService as CustomRouteServices;

class RoleController extends Controller
{

    public function __construct(CustomRouteServices $customRouteServices)
    {
        $this->customRouteServices=$customRouteServices;
        $this->CommonController = new CommonController();
        $this->list_num_of_records_per_page = Config::get('commonConfig.list_num_of_records_per_page');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(DataTables $datatables, Request $request)
    {
        $columns = [
            ['data' => 'rownum','name' => 'rownum','title' => 'Sr No.','searchable' => false],
            ['data' => 'role_name','name' => 'role_name','title' => 'Name'],
//            ['data' => 'company_logo','name' => 'company_logo','title' => 'Logo'],
            ['data' => 'actions','name' => 'actions','title' => 'Actions'],
        ];
        $getRequest = $request->all();
        $roles = Roles::orderBy('id', 'desc')->get();
        
        if ($datatables->getRequest()->ajax()) {

            return $datatables->of($roles)
                ->setRowId(function ($roles){
                    return 'row_'.$roles->id;
                })
                ->editColumn('rownum', function ($roles) {
                    static $i = 0;
                    $i++;
                    return $i;
                })
                ->editColumn('role_name', function ($roles) {
                    return $roles->role_name;
                })
                ->editColumn('actions', function ($roles) {
                    return view('admin.roles.actions', compact('roles'));
                })
                ->rawColumns(['rownum', 'role_name', 'actions'])
                ->make(true);

        }

        $html = $datatables->getHtmlBuilder()->columns($columns)->parameters($this->getParameters());
        // dd($html);
        return view('admin.roles.index', compact('html'));
    }

    protected function getParameters() {
        return [
            'serverSide' => true,
            'processing' => true,
            'ordering'   =>'isSorted',
//            "order"=> [2, "desc" ],
            "pageLength" => $this->list_num_of_records_per_page,
            // 'fixedHeader' => [
            //     'header' => true,
            //     'footer' => true
            // ]
            "filter" => [
                'class' => 'test_class'
            ]
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $routes = Route::getRoutes()->get();
        $roles = Roles::all();
        return view('admin.roles.add', compact('routes', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input_arr = $request->all();
        unset($input_arr['_token'], $input_arr['permissions']);

        $input_roles = $input_arr;
        $inserted_role = Roles::insertGetId($input_roles);

        // dd($inserted_role);
        if($input_arr['parent_id'] != null){
            $roles = Roles::where('id', $input_arr['parent_id'])->first();
            $roles_updated = Roles::where('id', $input_arr['parent_id'])->update(['child_id' => $inserted_role]);
        }

        $permissions =  $request->permissions;
        $i = 0;

        $input_permissions=array();
        foreach ($permissions as $permission){

            $flag=Permissions::where('name',$permission)->exists();

            if(!$flag){
                $permission_route = explode('.', $permission);
                $common_display_name='';
                $common_description='';
                if(!empty($permission_route[1])){
                    $permConfig=config("commonConfig.routes.$permission_route[1]");
                    if(!empty($permConfig)){

                        $common_display_name=$permConfig['display_name'];
                        $common_description=$permConfig['description'];

                    }else{
                        $common_display_name=ucfirst($permission_route[1]);
                        $common_description=ucfirst($permission_route[1]);
                    }
                }

                $input_permissions[$i]['name'] = $permission;
                $input_permissions[$i]['display_name'] = ucwords($common_display_name.' '. $permission_route[0]);
                $input_permissions[$i]['description'] = ucfirst($common_description.' '. $permission_route[0]);
                $i++;
            }
        }

        // dd($input_permissions);

        if(!empty($input_permissions)){
            $permissions[] = Permissions::insert($input_permissions);
        }
        $permissions = Permissions::whereIn('name', $permissions)->get();
        $i=0;
        foreach($permissions as $permission){
            $permission_role[$i]['role_id'] = $inserted_role;
            $permission_role[$i]['permission_id'] = $permission->id;
            $i++;
        }
        $permission_role = RolePermission::insert($permission_role);
        return redirect()->route('role.index')->withMessage(['type'=>'success','text'=>'Role Added!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Roles::where('id', $id)->with('permission')->first();
        $roles = Roles::all();
        $routes = Route::getRoutes()->get();
        // dd($role->permission->pluck('name')->toArray());
        $permittedRoutes=$role->permission->pluck('name')->toArray();
        return view('admin.roles.edit', compact('role','roles','routes','permittedRoutes') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $inserted_role =$id;

        $input_arr = $request->all();

        unset($input_arr['_token'], $input_arr['_method'], $input_arr['permissions']);

        $input_roles = $input_arr;
        Roles::where(['id'=>$id])->update($input_roles);
        if($input_arr['parent_id'] != null){
            $roles = Roles::where('id', $input_arr['parent_id'])->first();
            $roles_updated = Roles::where('id', $input_arr['parent_id'])->update(['child_id' => $id]);
        }

        $permissions =  $request->permissions;

        // append default admin rights from config
        // supposed $id==1 is admin_id role

        if($id==1){

            $routes = $this->customRouteServices->getRoutes();

            $admin_rights_default=config('commonConfig.admin_rights_default');

            $newArr=array_filter($routes,function($item) use ($admin_rights_default) {
                $input=explode('.',$item);
                if(in_array($input[0],$admin_rights_default)){
                    return $item;
                }else{
                    if(isset($input[1])){
                        if(in_array($input[1],$admin_rights_default)){
                            return $item;
                        }
                    }
                }
            });

            $permissions=array_merge($permissions,$newArr);
        }


        $i = 0;

        $input_permissions=[];

        foreach ($permissions as $permission){

            $flag=Permissions::where('name',$permission)->exists();

            if(!$flag){
            
                $permission_route = explode('.', $permission);

                $common_display_name='';
                $common_description='';
                if(!empty($permission_route[1])){
                    $permConfig=config("commonConfig.routes.$permission_route[1]");
                    if(!empty($permConfig)){

                        $common_display_name=$permConfig['display_name'];
                        $common_description=$permConfig['description'];

                    }else{
                        $common_display_name=ucfirst($permission_route[1]);
                        $common_description=ucfirst($permission_route[1]);
                    }
                }

            // echo $permission_route[0] . " : " . $common_display_name ." , ". $common_description . "<br/>";


                $input_permissions[$i]['name'] = $permission;
                $input_permissions[$i]['display_name'] = ucwords($common_display_name.' '. $permission_route[0]);
                $input_permissions[$i]['description'] = ucfirst($common_description.' '. $permission_route[0]);
                $i++;
            }
        }

        

        if(!empty($input_permissions))
        {
            Permissions::insert($input_permissions);
        }

        $permissions = Permissions::whereIn('name', $permissions)->get();
        $i=0;
        $permission_role=[];

        RolePermission::where('role_id',$inserted_role)->delete();

        foreach($permissions as $permission){

            // $flagRolePermission= RolePermission::where('role_id',$inserted_role)
            // ->where('permission_id',$permission->id)
            // ->exists();
            // flagRolePermission=true;
            // if(!$flagRolePermission){
                $permission_role[$i]['role_id'] = $inserted_role;
                $permission_role[$i]['permission_id'] = $permission->id;

resources/views/admin/roles/actions.blade.php
<a href="{{ route('role.edit', $roles->id) }}" class="btn btn-info">Edit</a>
<a href="javascript:void(0);" class="btn btn-danger" onclick="deleteRoles('{{ route('role.delete', $roles->id) }}')">Delete</a>

resources/views/admin/roles/add.blade.php
@extends('layouts.app')
@section('body')
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Add Roles
            </h3>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--Begin::Main Portlet-->
    <div class="m-portlet">
        {{--<div class="row">--}}
            <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="add_role_name" action="{{ route('role.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Role Name:
                            </label>
                            <input type="text" class="form-control m-input" name="role_name" placeholder="Enter Role name">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Role Description:
                            </label>
                            <input type="text" class="form-control m-input" name="description" placeholder="Enter Role description">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Display Name:
                            </label>
                            <input type="text" class="form-control m-input" name="display_name" placeholder="Enter display name">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                        </div>
                    </div>
                    {{--<div class="form-group m-form__group row">--}}
                        {{--<div class="col-md-9">--}}
                            {{--<label>--}}
                                {{--Child roles:--}}
                            {{--</label>--}}
                            {{--<select class="form-control m-input" name="option">--}}
                                {{--<option value="">--}}
                                    {{--Select--}}
                                {{--</option>--}}
                                {{--<option value="1">test</option>--}}
                            {{--</select>--}}
                            {{--<input type="text" class="form-control m-input" name="child_id" placeholder="Enter Role child">--}}
                            {{--<!-- <span class="m-form__help">--}}
                                {{--Please enter Company name--}}
                            {{--</span> -->--}}
                        {{--</div>--}}
                    {{--</div>--}}
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Parent Role:
                            </label>
                            <select class="form-control m-input" name="parent_id">
                                <option value="">
                                    Select
                                </option>
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->role_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Rirect to after login:
                            </label>
                            <select class="form-control m-input" name="redirect_to">
                                <option value="">
                                    Select
                                </option>
                                @foreach($routes as $key => $route)
                                    @if(isset($route->action['as']))
                                        @if(!in_array(explode('.', $route->action['as'])[0], config('commonConfig.route_prefixes_not_req.names')))
                                            @if(explode('.', $route->action['as'])[1] == 'index')
                                                <option value="{{ $route->action['as'] }}">{{ $route->action['as'] }}</option>
                                            @endif
                                        @endif
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Permissions:
                            </label>
                            <select class="form-control m-input" name="permissions[]" multiple size="5{{--{{ count($routes) }}--}}">
                                @foreach($routes as $route)
                                    @if(isset($route->action['as']))
                                        @if(!in_array(explode('.', $route->action['as'])[0], config('commonConfig.route_prefixes_not_req.names')))
                                            <option value="{{ $route->action['as'] }}">{{ $route->action['as'] }}</option>
                                        @endif
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                <a href="{{ route('role.index') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <!--end::Form-->
        {{--</div>--}}
    </div>
    <!--End::Main Portlet-->
</div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#add_role_name').validate({
                rules: {
                    role_name:{
                        required: true,
                    },
                    description:{
                        required: true
                    },
                    redirect_to:{
                        required: true
                    },
                    display_name:{
                        required: true
                    }
                },
                messages: {
                    role_name:{
                        required: "Please enter role name",
                    },
                    description:{
                        required: "Please eneter description"
                    },
                    redirect_to:{
                        required: "Please select redirect page."
                    },
                    display_name:{
                        required: "Please enter display name."
                    }
                }
            });
        });
    </script>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')
@section('body')
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    Edit Roles
                </h3>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Begin::Main Portlet-->
        <div class="m-portlet">
        {{--<div class="row">--}}
        <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="add_role_name" action="{{ route('role.update',[$role->id]) }}" method="post" enctype="multipart/form-data">
                @csrf

                @method('PUT')

                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Role Name:
                            </label>


                            <input type="text" class="form-control m-input" name="role_name" placeholder="Enter Role name" value="{{ $role->role_name }}">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Role Description:
                            </label>
                            {{-- <input type="text" class="form-control m-input" name="description" placeholder="Enter Role description"> --}}
                            <textarea name="description" id="description" class="form-control m-input" placeholder="Enter Role description">{{$role->description}}</textarea>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Display Name:
                            </label>
                        <input type="text" class="form-control m-input" name="display_name" placeholder="Enter display name" value="{{$role->display_name}}">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                        </div>
                    </div>

                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Parent Role:
                            </label>
                            <select class="form-control m-input" name="parent_id">
                                <option value="">
                                    Select
                                </option>
                                @foreach($roles as $roleRow)
                                    <option value="{{ $roleRow->id }}" {{!empty($role->parent_id)?($role->parent_id==$roleRow->id?'selected':'') :''}}  >{{ $roleRow->role_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Redirect to after login:
                            </label>
                            <select class="form-control m-input" name="redirect_to">
                                <option value="">
                                    Select
                                </option>
                                @foreach($routes as $route)
                                    @if(isset($route->action['as']))
                                        @if(!in_array(explode('.', $route->action['as'])[0], config('commonConfig.route_prefixes_not_req.names')))
                                            @if(explode('.', $route->action['as'])[1] == 'index')
                                                <option value="{{ $route->action['as'] }}"  {{($role->redirect_to==$route->action['as'])?'selected':''}}>{{ $route->action['as'] }}</option>
                                            @endif
                                        @endif
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-9">
                            <label>
                                Permissions:
                            </label>
                            <select class="form-control m-input" name="permissions[]" multiple size="5{{--{{ count($routes) }}--}}">
                                @foreach($routes as $route)
                                    @if(isset($route->action['as']))
                                        @if(!in_array(explode('.', $route->action['as'])[0], config('commonConfig.route_prefixes_not_req.names')))
                                            <option value="{{ $route->action['as'] }}" {{ (in_array($route->action['as'],$permittedRoutes)) ? 'selected' : ''}}>{{ $route->action['as'] }}</option>
                                        @endif
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                <a href="{{ route('role.index') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <!--end::Form-->
            {{--</div>--}}
        </div>
        <!--End::Main Portlet-->
    </div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#edit_role_name').validate({
                rules: {
                    role_name:{
                        required: true,
                    },
                    description:{
                        required: true
                    },
                    redirect_to:{
                        required: true
                    },
                    display_name:{
                        required: true
                    }
                },
                messages: {
                    role_name:{
                        required: true,
                    },
                    description:{
                        required: true
                    },
                    redirect_to:{
                        required: true
                    },
                    display_name:{
                        required: true
                    }
                }
            });
        });
    </script>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')
@section('body')
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    List of Roles
                </h3>
                <h3 class="m-subheader__title " style="float: right">
                    <a href="{{ route('role.create') }}" class="btn btn-primary">Add Role</a>
                </h3>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Begin::Main Portlet-->
        <div class="m-portlet m-portlet--compact m-portlet--mobile">
            <div class="m-portlet__body">
            {!! $html->table() !!}
            </div>
        </div>
    </div>
@endsection
@section('datatablejs')
    {!! $html->scripts() !!}
    <script>
        function deleteRoles(url) {
            if (confirm("Are you sure to delete?")) {
                console.log(url);
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    type: "GET",
                    // data: {
                    //     "id": id,
                    //     "_method": 'DELETE',
                    // },
                    url: url,
                    success: function (res) {
                        console.log(res);
                        $("#row_"+res).fadeOut("slow");
                    }
                });
            }
        }
    </script>
@endsection