routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/home', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@login_user')->name('login');
Route::get('/loginUser', 'Auth\LoginController@loginUser')->name('loginUser');
Route::get('/registerUser', 'Auth\LoginController@registerUser')->name('registerUser');
Route::get('/logout', 'Auth\LoginController@logout')->name('user.logout');

Route::group(['middleware' => ['check-permission']], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/role/delete/{id}', 'RoleController@delete')->name('role.delete');
    Route::resource('/role', 'RoleController');
    Route::resource('/user', 'UserController');
    Route::get('/server/delete/{id}', 'ServerController@delete')->name('server.delete');
    Route::resource('/server', 'ServerController');

});

Route::get('/generate_password', 'GeneratePasswordController@generate_password')->name('generate.password');
Route::get('/check_server_creds/{email}/{ip_addr}', 'GeneratePasswordController@check_server_creds')->name('check.server_creds');
Route::get('/check_otp/{otp}/{id}', 'GeneratePasswordController@check_otp')->name('check.otp');

app/Http/Controllers/ServerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ServerDetails;
use Auth;
use Config;
use App\Mail\SendServerDetails;
use Illuminate\Support\Facades\Mail;
use Yajra\DataTables\DataTables;
use App\Services\CustomRouteService as CustomRouteServices;

class ServerController extends Controller
{

    public function __construct(CustomRouteServices $customRouteServices)
    {
        $this->customRouteServices=$customRouteServices;
        $this->CommonController = new CommonController();
        $this->list_num_of_records_per_page = Config::get('commonConfig.list_num_of_records_per_page');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(DataTables $datatables, Request $request)
    {
        $columns = [
            ['data' => 'rownum','name' => 'rownum','title' => 'Sr No.','searchable' => false],
            ['data' => 'email_id','name' => 'email_id','title' => 'Email', 'searchable' => true],
            ['data' => 'ip_addr','name' => 'ip_addr','title' => 'IP Address', 'searchable' => true],
            ['data' => 'actions','name' => 'actions','title' => 'Actions'],
        ];
        $getRequest = $request->all();
        $server_details = ServerDetails::orderBy('id', 'desc')->get();
        
        if ($datatables->getRequest()->ajax()) {

            return $datatables->of($server_details)
                ->setRowId(function ($server_details){
                    return 'row_'.$server_details->id;
                })
                ->editColumn('rownum', function ($server_details) {
                    static $i = 0;
                    $i++;
                    return $i;
                })
                ->editColumn('email_id', function ($server_details) {
                    return $server_details->email_id;
                })
                ->editColumn('ip_addr', function ($server_details) {
                    return $server_details->ip_addr;
                })
                ->editColumn('actions', function ($server_details) {
                    return view('admin.servers.actions', compact('server_details'));
                })
                ->rawColumns(['rownum', 'email_id', 'ip_addr', 'actions'])
                ->make(true);

        }

        $html = $datatables->getHtmlBuilder()->columns($columns)->parameters($this->getParameters());
        // dd($html);
        return view('admin.servers.index', compact('html'));
    }

    protected function getParameters() {
        return [
            'serverSide' => true,
            'processing' => true,
            'ordering'   =>'isSorted',
//            "order"=> [2, "desc" ],
            "pageLength" => $this->list_num_of_records_per_page,
            // 'fixedHeader' => [
            //     'header' => true,
            //     'footer' => true
            // ]
            "filter" => [
                'class' => 'test_class'
            ]
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.servers.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $validated_fields = ServerDetails::validate($request);
        if($validated_fields->fails()){
            $errors = $validated_fields->errors();
            $request->flash();
            if($request->email != null){
                return $errors;
            }
            else{
                return redirect()->route('server.create')->withErrors($errors)->withInput();
            }
        }else{
            $server_details_entered = ServerDetails::where([['email_id', '=', $request->email_id], ['ip_addr', '=', $request->ip_addr]])->first();
            
            if($server_details_entered != null){
                $request->flash();
                return redirect()->route('server.create')->with('error', 'Email and IP address already exist!');
            }else{
                $input = $request->all();
                unset($input['_token']);
                $input['password'] = encrypt($request->password);
                // dd($input);
                $server_details = ServerDetails::create($input);
                

                // if(isset($server_details)){

                //     $data = array(
                //         'to_email' => $input['email_id'],
                //         'from_email' => Auth::user()->email,
                //         'ip_addr' => $input['ip_addr'],
                //         'subject' => 'Server Details',
                //         'url' => route('generate.password', $server_details->id)
                //     );
                    
                //     // try {
                //     //     Mail::to($data['to_email'])->send(new SendServerDetails($data));
                //     // }
                //     // catch (exception $e) {
                //     //     dd('msg:  ' .$e);
                //     // }

                // }
                
                return redirect()->route('server.index')->with('success', 'The server details added successfully!');
            }
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // dd($id);
        $server_details = ServerDetails::where('id', $id)->first();
        
        return view('admin.servers.edit', compact('server_details'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $server_details_entered = ServerDetails::where([['email_id', '=', $request->email_id], ['ip_addr', '=', $request->ip_addr]])->first();
            
        // if($server_details_entered != null){
        //     $request->flash();
        //     return redirect()->route('server.edit', $server_details_entered->id)->with('error', 'Email and IP address already exist!');
        // }else{
            $input = $request->all();
            unset($input['_token'], $input['_method'], $input['conf_password']);
            if($request->password == null){
                $input['password'] = $server_details_entered->password;
            }else{
                $input['password'] = encrypt($request->password);
            }
            $server_details_updated = ServerDetails::where('id', $id)->update($input);
            
            if($server_details_updated == 1){
                return redirect()->route('server.index')->with('success', 'The server details updated successfully!');
            }
        // }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/servers/actions.blade.php
<a href="{{ route('server.edit', $server_details->id) }}" class="btn btn-info">Edit</a>
<!-- <a href="javascript:void(0);" class="btn btn-secondary" onclick="deleteRoles('{{ route('server.delete', $server_details->id) }}')">Delete</a> -->

resources/views/admin/servers/add.blade.php
@extends('layouts.app')
@section('body')
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Add Server Details
            </h3>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--Begin::Main Portlet-->
    <div class="m-portlet">
        {{--<div class="row">--}}
        @if (session('error'))
            <span class="text-danger">{{ session('error') }}</span>
        @endif
            <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="add_server_details" action="{{ route('server.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-md-6">
                            <label>
                                Customer Email id:
                            </label>
                            <input type="text" class="form-control m-input" name="email_id" placeholder="Enter Email id" value="{{ old('email_id') }}">
                            <span class="text-danger">{{$errors->first('email_id')}}</span>
                        </div>
                        <div class="col-md-6">
                            <label>
                                IP address:
                            </label>
                            <input type="text" class="form-control m-input" name="ip_addr" placeholder="Enter IP address" value="{{ old('ip_addr') }}">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-6">
                            <label>
                                Passowrd:
                            </label>
                            <input type="password" class="form-control m-input" name="password" placeholder="Enter Password">
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                <a href="{{ route('server.index') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <!--end::Form-->
        {{--</div>--}}
    </div>
    <!--End::Main Portlet-->
</div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#add_server_details').validate({
                rules: {
                    email_id:{
                        required: true,
                    },
                    ip_addr:{
                        required: true
                    },
                    password:{
                        required: true
                    }
                },
                messages: {
                    email_id:{
                        required: "Please enter email id.",
                    },
                    ip_addr:{
                        required: "Please eneter ip address."
                    },
                    password:{
                        required: "Please enter password."
                    }
                }
            });
        });
    </script>
@endsection

resources/views/admin/servers/edit.blade.php
@extends('layouts.app')
@section('body')
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">
                Edit Server Details
            </h3>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!--Begin::Main Portlet-->
    <div class="m-portlet">
        {{--<div class="row">--}}
        @if (session('error'))
            <span class="text-danger">{{ session('error') }}</span>
        @endif
            <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="edit_server_details" action="{{ route('server.update', [$server_details->id]) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-md-6">
                            <label>
                                Customer Email id:
                            </label>
                            <input type="text" class="form-control m-input" name="email_id" placeholder="Enter Email id" value="{{ $server_details->email_id }}">
                            <span class="text-danger">{{$errors->first('email_id')}}</span>
                        </div>
                        <div class="col-md-6">
                            <label>
                                IP address:
                            </label>
                            <input type="text" class="form-control m-input" name="ip_addr" placeholder="Enter IP address" value="{{ $server_details->ip_addr }}">
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-6">
                            <label>
                                Passowrd:
                            </label>
                            <input type="password" class="form-control m-input" name="password" id="password" placeholder="Enter Password">
                        </div>
                        <div class="col-md-6">
                            <label>
                                Confirm Passowrd:
                            </label>
                            <input type="password" class="form-control m-input" name="conf_password" id="conf_password" placeholder="Confirm Password">
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                <a href="{{ route('server.index') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <!--end::Form-->
        {{--</div>--}}
    </div>
    <!--End::Main Portlet-->
</div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#edit_server_details').validate({
                rules: {
                    email_id:{
                        required: true,
                    },
                    ip_addr:{
                        required: true
                    },
                    // password:{
                    //     required: false
                    // },
                    conf_password: {
                        equalTo: "#password"
                    }
                },
                messages: {
                    email_id:{
                        required: "Please enter email id.",
                    },
                    ip_addr:{
                        required: "Please enter ip address."
                    },
                    // password:{
                    //     required: "Please enter password."
                    // },
                    conf_password: {
                        equalTo: "Password and confirm password must be same."
                    }
                }
            });
        });
    </script>
@endsection

resources/views/admin/servers/index.blade.php
@extends('layouts.app')
@section('body')
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                @if (session('success'))
                    <div class="alert alert-success" style="text-align: center" id="success">
                        {{ session('success') }}
                    </div>
                @endif
                <h3 class="m-subheader__title ">
                    List of Server Details
                </h3>
                <h3 class="m-subheader__title " style="float: right">
                    <a href="{{ route('server.create') }}" class="btn btn-primary">Add Server Details</a>
                </h3>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Begin::Main Portlet-->
        <div class="m-portlet m-portlet--compact m-portlet--mobile">
            <div class="m-portlet__body">
            {!! $html->table() !!}
            </div>
        </div>
    </div>
@endsection
@section('datatablejs')
    {!! $html->scripts() !!}
    <script>
        function deleteRoles(url) {
            if (confirm("Are you sure to delete?")) {
                console.log(url);
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    type: "GET",
                    // data: {
                    //     "id": id,
                    //     "_method": 'DELETE',
                    // },
                    url: url,
                    success: function (res) {
                        console.log(res);
                        $("#row_"+res).fadeOut("slow");
                    }
                });
            }
        }

        $(document).ready(function(){
            $('#success').delay(500).slideUp(500);
        });
    </script>
@endsection