routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/home', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@login_user')->name('login');
Route::get('/loginUser', 'Auth\LoginController@loginUser')->name('loginUser');
Route::get('/registerUser', 'Auth\LoginController@registerUser')->name('registerUser');
Route::get('/logout', 'Auth\LoginController@logout')->name('user.logout');

Route::group(['middleware' => ['check-permission']], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/role/delete/{id}', 'RoleController@delete')->name('role.delete');
    Route::resource('/role', 'RoleController');
    Route::resource('/user', 'UserController');
    Route::get('/server/delete/{id}', 'ServerController@delete')->name('server.delete');
    Route::resource('/server', 'ServerController');

});

Route::get('/generate_password', 'GeneratePasswordController@generate_password')->name('generate.password');
Route::get('/check_server_creds/{email}/{ip_addr}', 'GeneratePasswordController@check_server_creds')->name('check.server_creds');
Route::get('/check_otp/{otp}/{id}', 'GeneratePasswordController@check_otp')->name('check.otp');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Validator;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function validate($request){
        $validatedata = Validator::make($request->input(), [
            'name' => 'required',
            'email' => 'required|unique:users,email',
//            'password' => 'required',
        ]);

        return $validatedata;
    }

    public function roles()
    {
        return $this->belongsToMany('App\Roles', 'role_users', 'user_id', 'role_id')/*->withPivot('start_date', 'end_date')*/;
    }

//    public function roles()
//    {
//        return $this->belongsToMany('App\Roles', 'role_users', 'user_id', 'role_id')/*->withPivot('start_date', 'end_date')*/;
//    }

    public function roleusers()
    {
        return $this->belongsTo('App\RoleUser', 'user_id', 'role_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Roles;
use App\RoleUser;
use App\User;
use Illuminate\Http\Request;
use Symfony\Component\VarDumper\Cloner\Data;
use Yajra\DataTables\DataTables;
use Config;
use Auth;

class UserController extends Controller
{

    public function __construct()
    {
        $this->CommonController = new CommonController();
        $this->list_num_of_records_per_page = Config::get('commonConfig.list_num_of_records_per_page');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(DataTables $datatables, Request $request)
    {
        $columns = [
            ['data' => 'rownum','name' => 'rownum','title' => 'Sr No.','searchable' => false],
            ['data' => 'user_name','name' => 'user_name','title' => 'Name'],
            ['data' => 'actions','name' => 'actions','title' => 'Actions'],
        ];
        $getRequest = $request->all();
        $users = User::orderBy('id', 'desc')->get();

        if ($datatables->getRequest()->ajax()) {

            return $datatables->of($users)
                ->setRowId(function ($users){
                    return 'row_'.$users->id;
                })
                ->editColumn('rownum', function ($users) {
                    static $i = 0;
                    $i++;
                    return $i;
                })
                ->editColumn('user_name', function ($users) {
                    return $users->name;
                })
                ->editColumn('actions', function ($users) {
                    return view('user.actions', compact('users'));
                })
                ->rawColumns(['rownum', 'user_name', 'actions'])
                ->make(true);

        }

        $html = $datatables->getHtmlBuilder()->columns($columns)->parameters($this->getParameters());
        return view('user.index', compact('html'));
    }


    protected function getParameters() {
        return [
            'serverSide' => true,
            'processing' => true,
            'ordering'   =>'isSorted',
//            "order"=> [2, "desc" ],
            "pageLength" => $this->list_num_of_records_per_page,
            // 'fixedHeader' => [
            //     'header' => true,
            //     'footer' => true
            // ]
            "filter" => [
                'class' => 'test_class'
            ]
        ];
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Roles::all();

        return view('user.add', compact('user', 'roles', 'role_users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated_fields = User::validate($request);
        if($validated_fields->fails()){
//            dd($validated_fields->fails());
            $errors = $validated_fields->errors();
            $request->flash();
            if($request->email != null){
                return $errors;
            }
            else{
                return redirect()->route('user.create')->withErrors($errors)->withInput();
            }
        }else{
            $input = $request->all();
            unset($input['_token']);
            $password = explode('.', explode('@', $input['email'])[0]);
            
            if(isset($password[1])){
                $input['password'] = bcrypt($password[0].substr($password[1], 0, 1).'123');
            }else{
                $input['password'] = bcrypt($password[0].'123');
            }
            // bcrypt(substr($input['name'], 0, 6).'123')
            
            $user = User::create($input);
            $input_role_user = array(
                'user_id' => $user->id,
                'role_id' => $input['role_id']
            );
            RoleUser::create($input_role_user);
            return redirect()->route('user.index')->with('success', 'The user created successfully!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::where('id', $id)->first();
        $roles = Roles::all();
        $role_users = RoleUser::all();

        return view('user.edit', compact('user', 'roles', 'role_users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input_arr = $request->all();
        $input_roles_user_arr = array(
            'user_id' => $id,
            'role_id' => $input_arr['role_id']
        );
        // dd(config('commonConfig.super_admin'));
        if(Auth::user()->id != config('commonConfig.admin') || Auth::user()->email == config('commonConfig.super_admin')){
            // dd($input_roles_user_arr);
            RoleUser::where('user_id', $id)->update($input_roles_user_arr);
            $password = explode('.', explode('@', $input_arr['email'])[0]);
            $input_arr['password'] = bcrypt($password[0].substr($password[1], 0, 1).'123');
            $arr = array(
                'name' => $input_arr['name'],
                'email' => $input_arr['email'],
                'password' => $input_arr['password']
            );
            User::where('id', $id)->update($arr);
        }
        // dd('========');
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/actions.blade.php
<a href="{{ route('user.edit', $users->id) }}" class="btn btn-info">Edit</a>
{{--<a href="javascript:void(0);" class="btn btn-secondary" onclick="deleteVendor('{{ route('vendor.delete', $vendor_details->id) }}')">Delete</a>--}}

resources/views/user/add.blade.php
@extends('layouts.app')
@section('body')
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    Add User Name
                </h3>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Begin::Main Portlet-->
        <div class="m-portlet">
        {{--<div class="row">--}}
        <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="edit_vendor_name" action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-md-6">
                            <label>
                                User Name:
                            </label>
                            <input type="text" class="form-control m-input" name="name" placeholder="Enter User name">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                            <span id="name" class="text-danger">{{$errors->first('name')}}</span>
                        </div>
                        <div class="col-md-6">
                            <label>
                                Email id:
                            </label>
                            <input type="text" class="form-control m-input" name="email" placeholder="Enter User email">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                            <span id="email" class="text-danger">{{$errors->first('email')}}</span>
                        </div>
                        <div class="col-md-6">
                            <label>
                                Roles:
                            </label>
                            <select class="form-control m-input" name="role_id">
                                <option value="">
                                    Select
                                </option>
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->role_name }}</option>
                                @endforeach
                            </select>
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                            <span id="role_id" class="text-danger">{{$errors->first('role_id')}}</span>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                {{--<button type="reset" class="btn btn-secondary">--}}
                                {{--Cancel--}}
                                {{--</button>--}}
                                <a href="{{ route('user.index') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <!--end::Form-->
            {{--</div>--}}
        </div>
        <!--End::Main Portlet-->
    </div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#edit_vendor_name').validate({
                rules: {
                    name:{
                        required: true,
                    },
                    email:{
                        required: true,
                        email: true
                    },
                    role_id:{
                        required: true,
                    },
                    // company_logo:{
                    //     required: true,
                    //     extension: "jpg,jpeg"
                    // },
                },
                messages: {
                    // company_logo:{
                    //     extension: "Please upload files with .jpg and .jpeg extension."
                    // },
                }
            });

            $('input[name=email]').keyup(function(){
                var email = $('input[name=email]').val();
                var url = "{{ route('user.store') }}";
                console.log(email);
                if(email != null && email.length > 2){
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        url: '{{ route('user.store') }}',
                        method: 'post',
                        data: {
                            email: email,
                        },
                        success: function(res){
                            if(res.email != undefined){
                                $('#email').text(res.email[0]);
                            }else{
                                $('#email').text('');
                            }
                        }
                    });
                }
            });
        });
    </script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('body')
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    Edit User Name
                </h3>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Begin::Main Portlet-->
        <div class="m-portlet">
        {{--<div class="row">--}}
        <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="edit_vendor_name" action="{{ route('user.update', $user->id) }}" method="post" enctype="multipart/form-data">
                @method('PATCH')
                @csrf
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-md-6">
                            <label>
                                User Name:
                            </label>
                            <input type="text" class="form-control m-input" name="name" placeholder="Enter User name" value="{{ $user->name }}">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                        </div>
                        <div class="col-md-6">
                            <label>
                            Email id:
                            </label>
                            <input type="text" class="form-control m-input" name="email" placeholder="Enter User email" value="{{ $user->email }}">
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                            <span id="email" class="text-danger">{{$errors->first('email')}}</span>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-md-6">
                            <label>
                                Roles:
                            </label>
                            <select class="form-control m-input" name="role_id">
                                <option value="">
                                    Select
                                </option>
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}" @foreach($role_users as $role_user) @if($role->id == $role_user->role_id) {{ "selected" }} @endif @endforeach>{{ $role->role_name }}</option>
                                @endforeach
                            </select>
                            <!-- <span class="m-form__help">
                                Please enter Company name
                            </span> -->
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                {{--<button type="reset" class="btn btn-secondary">--}}
                                {{--Cancel--}}
                                {{--</button>--}}
                                <a href="{{ route('user.index') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <!--end::Form-->
            {{--</div>--}}
        </div>
        <!--End::Main Portlet-->
    </div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#edit_vendor_name').validate({
                rules: {
                    vendor_name:{
                        required: true,
                    },
                    // company_logo:{
                    //     required: true,
                    //     extension: "jpg,jpeg"
                    // },
                },
                messages: {
                    // company_logo:{
                    //     extension: "Please upload files with .jpg and .jpeg extension."
                    // },
                }
            });
        });
    </script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('body')
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                @if (session('success'))
                    <div class="alert alert-success" style="text-align: center" id="success">
                        {{ session('success') }}
                    </div>
                @endif
                <h3 class="m-subheader__title ">
                    List of Users
                </h3>
                <h3 class="m-subheader__title " style="float: right">
                    <a href="{{ route('user.create') }}" class="btn btn-primary">Add User</a>
                </h3>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Begin::Main Portlet-->
        <div class="m-portlet m-portlet--compact m-portlet--mobile">
            <div class="m-portlet__body">
            {!! $html->table() !!}
            </div>
        </div>
    </div>
@endsection
@section('datatablejs')
    {!! $html->scripts() !!}
    <script>
        function deleteVendor(url) {
            if (confirm("Are you sure to delete?")) {
                console.log(url);
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    type: "GET",
                    // data: {
                    //     "id": id,
                    //     "_method": 'DELETE',
                    // },
                    url: url,
                    success: function (res) {
                        console.log(res);
                        $("#row_"+res).fadeOut("slow");
                    }
                });
            }
        }

        $(document).ready(function(){
            $('#success').slideUp("slow");
        });
    </script>
@endsection